name: C/C++ CI

on: [push]

jobs:
  build_proto:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Install dependencies
      run: make deps

    - name: Build rs4se
      run: make install
